# Generated by Django 4.2.27 on 2025-12-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sport_type', models.CharField(choices=[('badminton', 'Badminton'), ('tennis', 'Tennis'), ('pickleball', 'Pickleball')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
