# Generated by Django 4.2.27 on 2026-01-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('court', 'booking_date', 'booking_time'), name='unique_court_booking'),
        ),
    ]
