# Generated by Django 4.2.27 on 2026-01-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_unique_court_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.CharField(choices=[('08:00', '08:00 – 09:00'), ('09:00', '09:00 – 10:00'), ('10:00', '10:00 – 11:00'), ('11:00', '11:00 – 12:00'), ('12:00', '12:00 – 13:00'), ('13:00', '13:00 – 14:00'), ('14:00', '14:00 – 15:00'), ('15:00', '15:00 – 16:00'), ('16:00', '16:00 – 17:00'), ('17:00', '17:00 – 18:00'), ('18:00', '18:00 – 19:00'), ('19:00', '19:00 – 20:00'), ('20:00', '20:00 – 21:00'), ('21:00', '21:00 – 22:00')], max_length=5),
        ),
    ]
